server:
  port: 27772
  #  context-path:


#spring:
#  profiles:
#    acvive:
#  aplication:
#    name:

#soreal:
#  translate:
#    papago:
#      client-id:
#      client-secret:
#    google:
#    amazon:



