server:
  port: 27772
  #  context-path:

#spring:
#  profiles:
#    active:
#  application:
#    name:

soreal:
  path:
    common: "C:/Users/rladu/OneDrive/Documents/otome/"
    peterpen: "C:/Users/rladu/OneDrive/Documents/otome/peterpen/"
#      rawscript:
#      convertjp:
#      tranlateko:
#      mydicko:
#  translate:
#    papago:
#      client-id:
#      client-secret:
#    google:
#    amazon:

